@startuml
!include <office/Servers/application_server>

nwdiag {

    network Intranet {
        address = "192.168.222.0/24";
        server1 [address = "192.168.222.10" description = "<$application_server>\n  AD DC\n Windows\n  Server\n   2022"];
        server2 [address = "192.168.222.20" description = "<$application_server>\nKeycloak\nWindows\n Server\n  2022"];
        client [address = dhcp description = "  <&person*5>\nWindws11\n Client PC"];
    }
}

@enduml