site_name: 過去のログ

nav:
  - "言語":
    - Python:
      - PyKCS11: lang/python/pykcs11.md
      - python-pkcs11: lang/python/python-pkcs11.md

theme:
  name: material
  lang: ja
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: blue
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: blue grey
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    # ナビゲーションのグループ化表示制御
    - navigation.sections
    # コードブロックのコピーボタン
    - content.code.copy

extra_css:
  - css/custom.css

plugins:
  - tags
  - search:
      lang: ja
  # pip install mkdocs-git-revision-date-localized-plugin
  - git-revision-date-localized:
      # MKDOCS_CI 環境変数が true にセットされていた場合にプラグインが有効
      enabled: !ENV [MKDOCS_CI, false]
      enable_creation_date: true

markdown_extensions:
  - toc:
      toc_depth: 4
  - admonition
  - pymdownx.details
  - footnotes
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html

