site_name: 過去のログ

nav:
  - OS:
    - BSD:
      - FreeBSD: os/bsd/freebsd14.md
    - Linux:
      - Debian: os/linux/debian_12.md
      - Fedora 40 Server: os/linux/fedora_40_server.md
      - XUbutnu 22.04: os/linux/xubuntu_2204.md
    - MacOS Tips: os/macos/macos_tips.md
    - Windows Tips: os/windows/windows_tips.md

  - Server:
    - PostgreSQL: server/postgresql.md
    - Samba: server/samba.md
    - SSH:
      - 公開鍵認証: server/ssh_public_key_authentication.md

  - "言語":
    - Python:
      - OCI SDK: lang/python/oci_sdk_python.md
      - PyKCS11: lang/python/pykcs11.md
      - python-pkcs11: lang/python/python-pkcs11.md

  - "仮想化":
    - Containerd:
      - Containerd: virtualization/containerd.md
      - KataContainer: virtualization/containerd_katacontainer.md
    - LXC: virtualization/lxc.md
    - QEMU: virtualization/qemu.md
    - Proxmox: virtualization/proxmox.md
    - Kubernetes:
      - minikube: virtualization/k8s/minikube.md
      - "Kubernetes環境設定": virtualization/k8s/kubernetes_env.md
      - kubeadm:
        - kubeadm: virtualization/k8s/kubeadm.md
        - ControlPlane: virtualization/k8s/kubernetes_controlplane.md
        - WorkerNode: virtualization/k8s/kubernetes_workernode.md
        - Pod: virtualization/k8s/kubernetes_01_pod.md
        - Service: virtualization/k8s/kubernetes_02_service.md
        - Namespace: virtualization/k8s/kubernetes_03_namespace.md

    - KVM:
      - "環境準備": virtualization/kvm/01_prepare.md
      - "Gateway VM": virtualization/kvm/02_gateway_vm.md
      - "Linux VM": virtualization/kvm/03_linux_vm.md
      - "BSD VM (まだ起動できない)": virtualization/kvm/03_bsd_vm.md
      - "Windows VM (まだ起動できない)": virtualization/kvm/03_windows_vm.md

  - "アプリケーション":
    - ClamAV: app/clamav.md
    - OpenSSL:
      - 自己証明書: app/openssl_self-certification.md
    - SoftHSM: app/softhsm.md
    - Tripwire: app/tripwire.md
    - vim:
      - ctags: app/vim_ctags.md
    - Linux Tools:
      - sysstat: app/linux/sysstat.md

  - "クラウドサービス":
    - AWS:
      - localstack: cloudservice/aws/localstack.md
    - OCI:
      - OCI SDK: lang/python/oci_sdk_python.md

theme:
  name: material
  lang: ja
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: blue
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: blue grey
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    # ナビゲーションのグループ化表示制御
    - navigation.sections
    # コードブロックのコピーボタン
    - content.code.copy

extra_css:
  - css/custom.css

plugins:
  - tags
  - search:
      lang: ja
  # pip install mkdocs-git-revision-date-localized-plugin
  - git-revision-date-localized:
      # MKDOCS_CI 環境変数が true にセットされていた場合にプラグインが有効
      enabled: !ENV [MKDOCS_CI, false]
      enable_creation_date: true

markdown_extensions:
  - toc:
      toc_depth: 4
  - admonition
  - pymdownx.details
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html

