" neocomplete有効化
let g:neocomplete#enable_at_startup = 1

" visualモードを無効にする
set mouse-=a

" 文字コード
set encoding=utf-8
set fenc=utf-8

" カラースキーム
colorscheme desert
"colorscheme koehler
syntax on

" Tab系
" tab幅
set tabstop=4

" タブの可視化
" for macOS
"set list listchars=tab:\?\-
" for Linux
"set list listchars=tab:\`\

" Tab文字を半角スペースにする
"set expandtab

" バックアップファイルを作らない
set nobackup
" スワップファイルを作らない
"set noswapfile
" 編集中のファイルが変更されたら自動で読み直す
set autoread

" 行番号を表示
set nonumber
" 現在の行を強調表示
set cursorline
" 現在の行を強調表示（縦）
"set cursorcolumn
" 行末の1文字先までカーソルを移動できるように
"set virtualedit=onemore

" 括弧入力時の対応する括弧を表示
set showmatch

" コマンドラインの補完
set wildmode=list:longest


" ステータスラインを常に表示
set laststatus=2
" ステータスラインにコマンドを表示
set showcmd
"ファイルナンバー表示
set statusline=[%n]
"ホスト名表示
set statusline+=%{matchstr(hostname(),'\\w\\+')}@
"ファイル名表示
set statusline+=%<%F
"変更のチェック表示
set statusline+=%m
"読み込み専用かどうか表示
set statusline+=%r
"ヘルプページなら[HELP]と表示
set statusline+=%h
"プレビューウインドウなら[Prevew]と表示
set statusline+=%w

" ここから右寄せ
set statusline+=%=
" ASCII code
set statusline+=[ASCII=\%02.2B]
"ファイルフォーマット表示
set statusline+=[%{&fileformat}]
"文字コード表示
set statusline+=[%{has('multi_byte')&&\&fileencoding!=''?&fileencoding:&encoding}]
"ファイルタイプ表示
"set statusline+=%y
" 現在行数/全行数
set statusline+=[COL=%c]
set statusline+=[ROW=%l/%L(%p%%)]


""" netrw
" netrwは常にtree view
let g:netrw_liststyle = 3
" CVSと.で始まるファイルは表示しない
let g:netrw_list_hide = 'CVS,\(^\|\s\s\)\zs\.\S\+'
" 'v'でファイルを開くときは右側に開く。(デフォルトが左側なので入れ替え)
let g:netrw_altv = 1
" 'o'でファイルを開くときは下側に開く。(デフォルトが上側なので入れ替え)
let g:netrw_alto = 1

